# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import shoppinglist.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='id',
            field=models.PositiveIntegerField(default=shoppinglist.models.create_unique_urlindex, primary_key=True, serialize=False),
        ),
    ]
