# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20170329_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='origin_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_derivations', to='recipe.Recipe'),
        ),
    ]
