# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0002_auto_20170322_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebook',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
